modLoader = "javafml"
loaderVersion = "[4,)"
license = "MPL-2.0"
issueTrackerURL = "https://github.com/WindClan/bedsalwaysexplode/issues"
showAsResourcePack=false
clientSideOnly=false

[[mods]]
modId = "bedsalwaysexplode"
version = "${version}"
displayName = "Beds Always Explode"
authors = "WindClan / average warrior cats fan"
description = '''
Makes beds always explode
'''
logoFile = "assets/bedsalwaysexplode/icon.png"


[[dependencies.bedsalwaysexplode]]
modId = "minecraft"
mandatory=true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"